# Required
version: 2

mkdocs:
  configuration: docs/mkdocs.yml
  fail_on_warning: false

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - requirements: docs/requirements.txt
