- name: Add user mdqsync for rsync
  ansible.builtin.user:
    name: mdqsync
    state: present
  tags: [docker-be, docker-fe]

- name: Create folder .ssh
  ansible.builtin.file:
    path: /home/mdqsync/.ssh
    state: directory
    owner: mdqsync
    group: mdqsync
    recurse: yes
  tags: [docker-be, docker-fe]

- name: Create BE deployment folders
  ansible.builtin.file:
    path: /opt/idem-mdx-be
    state: directory
    recurse: yes
  tags: [docker-be]

- name: Create FE deployment folder
  ansible.builtin.file:
    path: "/opt/{{ item }}"
    state: directory
    mode: '0777'
    recurse: yes
  loop:
    - idem-mdx-fe
    - idem-mdq-data
  tags: [docker-fe]

- name: Copy BE files from template
  ansible.builtin.template:
    src: "{{ item['src'] }}"
    dest: "/opt/idem-mdx-be/{{ item['dest'] }}"
  loop:
    - { src: .be.env, dest: .be.env }
    - { src: "docker-compose-be-{{ deploy_type }}.yml", dest: docker-compose.yml }
  tags: [docker-be]

- name: Copy FE files from template
  ansible.builtin.template:
    src: "{{ item['src'] }}"
    dest: "/opt/idem-mdx-fe/{{ item['dest'] }}"
  loop:
    - { src: .fe.env, dest: .fe.env }
    - { src: "docker-compose-fe-{{ deploy_type }}.yml", dest: docker-compose.yml }
  tags: [docker-fe]
