- name: Add user mdqsync for rsync
  ansible.builtin.user:
    name: mdqsync
    state: present
  tags: [docker-be, docker-fe]

- name: Create folder .ssh
  ansible.builtin.file:
    path: /home/mdqsync/.ssh
    state: directory
    owner: mdqsync
    group: mdqsync
    recurse: yes
  tags: [docker-be, docker-fe]

- name: Create deployment folders
  ansible.builtin.file:
    path: "/opt/{{ item }}"
    state: directory
    recurse: yes
  loop:
    - idem-mdx-be
    - idem-mdx-fe
  tags: [docker-be, docker-fe]

- name: Create deployment folder
  ansible.builtin.file:
    path: /opt/idem-mdq-data
    state: directory
    mode: '0777'
    recurse: yes
  tags: [docker-be, docker-fe]

- name: Copy .env from template
  ansible.builtin.template:
    src: ".{{ item['src'] }}.env"
    dest: "/opt/{{ item['dest'] }}/.{{ item['src'] }}.env"
  loop:
    - { src: be, dest: idem-mdx-be }
    - { src: fe, dest: idem-mdx-fe }
  tags: [docker-be, docker-fe]

- name: Copy docker-compose.yml file from template
  ansible.builtin.template:
    src: "{{ item['src'] }}"
    dest: "/opt/{{ item['dest'] }}/docker-compose.yml"
  loop:
    - { src: "docker-compose-be-{{ deploy_type }}.yml", dest: idem-mdx-be }
    - { src: "docker-compose-fe-{{ deploy_type }}.yml", dest: idem-mdx-fe }
  tags: [docker-be, docker-fe]
