version: '3.9'
services:
    nginx:
        image: "gitlab.dir.garr.it:4567/idem/idem-mdx/fe-nginx:{{ nginx_version }}"
        container_name: "{{ fe_containername }}-nginx"
        hostname: idem-mdx-nginx
        env_file:
            - ".fe.env"
        restart: unless-stopped
        ports: 
            - "8080:8080"
            - "8444:8444"
        volumes:
            - "/opt/idem-mdq-data:/app/idem-mdq:ro"
