version: '3.9'
services:
    nginx:
        image: "{{ image_prefix }}nginx:{{ nginx_version }}"
        container_name: "{{ fe_containername }}-nginx"
        env_file:
            - ".fe.env"
        restart: unless-stopped
        ports: 
            - "80:8080"
            - "443:8444"
        volumes:
            - "/opt/idem-mdq-data:/app/idem-mdq:ro"
