services:
    nginx:
        image: "gitlab.dir.garr.it:4567/idem/idem-mdx/fe-nginx:{{ nginx_version }}"
        container_name: "{{ fe_containername }}-nginx"
        hostname: idem-mdx-nginx
        env_file:
            - ".fe.env"
        restart: always
        ports: 
            - "80:80"
            - "443:443"
        volumes:
            - "/opt/idem-mdq-data:/app/idem-mdq:ro"
            - "/opt/idem-certbot/:/etc/letsencrypt"