services:
    nginx:
        image: "{{ image_prefix }}nginx:{{ nginx_version }}"
        container_name: "{{ fe_containername }}-nginx"
        env_file:
            - ".fe.env"
        restart: always
        ports: 
            - "80:80"
            - "443:443"
        volumes:
            - "/opt/idem-mdq-data:/app/idem-mdq:ro"
