site_name: IDEM MDX
site_author: IDEM

docs_dir: '../../docs/en'
site_dir: '../../site/en'

# Page tree
nav:
# - Nome della sezione: nome del file.md
# Esempio:
# - HowTo IDEM RT: howto_rt.md
  - Introduction: index.md
  - Shibboleth Configuration: shibboleth.md
  - SimpleSAMLphp Configuration: simplesamlphp.md
  - Satosa Configuration: satosa.md
  - Embedded Discovery Service w/ MDX:
    - EDS/index.md
    - EDS/shibboletheds.md
    - EDS/sspeds.md
  - Aggregates: aggregates.md
  - Downloads: downloads.md

theme:
  name: material
  language: en
  custom_dir: '../../overrides/'
  logo: assets/logo-garr.png
  favicon: assets/favicon.ico
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - announce.dismiss
    #- content.action.edit
    #- content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.path
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    # - navigation.prune
    # - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

extra:
  alternate:
    # Switch to English
    - name: English
      link: /en/ 
      lang: en

    # Switch to italian  
    - name: Italian
      link: /it/
      lang: it

  # Footer
  generator: false # Disable Made with Material for MkDocs

plugins:
  - search:
      lang: en
  - git-revision-date-localized:
      type: date
      enable_creation_date: false
      fallback_to_build_date: true
  # - git-authors
  - markdownextradata
  - resize-images:
      source-dir: assets-resize
      target-dir: assets
      enable_cache: True
      size: [900, 600]
      extensions: [".jpg", ".jpeg", ".png", ".gif", ".svg"]
  #- privacy
  #- open-in-new-tab

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  #     emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: Copyright &copy; 2024 Consortium GARR
