- name: Deployment IDEM-MDX - BE Production
  hosts: 
    - ba1-r2
  become: yes
  become_method: sudo
  remote_user: debian 
  roles:
    - requirements
    - setup
  vars_files:
    - idem-mdx-inventories/prod/secrets/prod.yml
  tasks:
    - name: Run BackEnd image
      ansible.builtin.shell: "docker compose up -d"
      args:
        chdir: "/opt/{{ be_folder }}"
      tags: [docker-be]
  
    - name: Copy pubkey to host
      ansible.builtin.shell: "docker cp {{ be_containername }}-crsync:/ssh/mdqsync-key.pub /home/mdqsync/.ssh/mdqsync.pub"
      tags: [docker-be]

    - name: Grab pubkey from remote container
      ansible.builtin.fetch:
        src: /home/mdqsync/.ssh/mdqsync.pub
        dest: ./pubkey
        flat: true
      tags: [always]


- name: Deployment IDEM-MDX - FE Production
  hosts: 
    - remote_hosts
  become: yes
  become_method: sudo
  remote_user: debian 
  roles:
    - requirements
    - setup
  vars_files:
    - idem-mdx-inventories/prod/secrets/prod.yml
  tasks:
    - name: Run FrontEnd image
      ansible.builtin.shell: "docker compose up -d"
      args:
        chdir: "/opt/{{ fe_folder }}"
      tags: [docker-fe]

    - name: Copy the pubkey to all hosts
      ansible.builtin.copy:
        src: ./pubkey
        dest: /home/mdqsync/.ssh/mdqsync.pub
      tags: [always]

    - name: Add pubkey to authorized keys
      ansible.builtin.shell: "cat /home/mdqsync/.ssh/mdqsync.pub >> /home/mdqsync/.ssh/authorized_keys"
      tags: [always]

