site_name: IDEM MDX
site_author: IDEM

repo_url: https://gitlab.dir.garr.it/IDEM/idem-mdx
repo_name: idem/idem-mdx
edit_uri: -/edit/main/docs/docs
#view_uri: -/raw/main/docs/docs

# Page tree
nav:
# - Nome della sezione: nome del file.md
# Esempio:
# - HowTo IDEM RT: howto_rt.md
  - Introduction: index.md
  - Requirements: project-requirements.md
  - Development Instruction: dev-instruction.md
  - Staging/Prod Instruction: instruction.md
  - Disaster Recovery: disaster-recovery.md

theme:
  name: material
  language: en
  logo: assets/logo-garr.png
  favicon: assets/favicon.ico
  icon:
    repo: material/gitlab
    edit: material/pencil
    view: material/eye
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.path
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    # - navigation.prune
    # - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

extra:
  homepage: https://docs.dir.garr.it
  # Footer
  generator: false # Disable Made with Material for MkDocs

  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/ReteGARR
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/ReteGARR
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/retegarr/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/retegarr
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/GARRTV
    - icon: fontawesome/brands/telegram
      link: https://t.me/retegarr

plugins:
  - search
  - git-revision-date-localized:
      type: date
      enable_creation_date: false
      fallback_to_build_date: true
  # - git-authors
  - markdownextradata
  - resize-images:
      source-dir: assets-resize
      target-dir: assets
      enable_cache: True
      size: [900, 600]
      extensions: [".jpg", ".jpeg", ".png", ".gif", ".svg"]
  #- privacy
  #- open-in-new-tab

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  #     emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: Copyright &copy; 2024 Consortium GARR
